[package]
name = "compact-tree-sitter"
version = "0.1.0"
description = "Declaration-level Compact grammar for tree-sitter"
build = "bindings/rust/build.rs"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json",
  "LICENSE*",
  "README.md",
]

[lints]
workspace = true

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language.workspace = true

[build-dependencies]
cc.workspace = true

[dev-dependencies]
tree-sitter.workspace = true
