//! Declaration-level tree-sitter grammar for Compact (Midnight).
//!
//! Declarations are named nodes with a `name` field; circuit and constructor
//! bodies, parameter lists and statements stay opaque brace-balanced runs.

#![deny(unsafe_op_in_unsafe_fn)]

use tree_sitter_language::LanguageFn;

unsafe extern "C" {
    fn tree_sitter_compact() -> *const ();
}

/// The tree-sitter language for Compact.
// SAFETY: `tree_sitter_compact` is generated by tree-sitter-cli into `src/parser.c`,
// which `build.rs` links into this crate, and it returns a `'static` language pointer.
pub const LANGUAGE: LanguageFn = unsafe { LanguageFn::from_raw(tree_sitter_compact) };

/// The node-type metadata that tree-sitter-cli generated alongside the parser.
pub const NODE_TYPES: &str = include_str!("../../src/node-types.json");

/// The highlight query shipped with the grammar.
pub const HIGHLIGHTS_QUERY: &str = include_str!("../../queries/highlights.scm");

#[cfg(test)]
mod tests {
    #[test]
    fn language_loads_into_a_parser() {
        let mut parser = tree_sitter::Parser::new();
        parser
            .set_language(&super::LANGUAGE.into())
            .expect("the generated parser matches the tree-sitter ABI this crate builds against");
    }
}
